name: Ruby

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.3'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Install sqlite3
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev
    - name: Install Ruby dependencies
      run: |
        bundle config set --local build.sqlite3 --enable-system-libraries
        bundle install --jobs 4 --retry 3
    - name: Run the default task
      run: bundle exec rake
